;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-command-master
        TeX-insert-backslash
        TeX-insert-sub-or-superscript
        backward-sentence
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        coffee-newline-and-indent
        comment-dwim
        copy-rectangle-to-register
        count-words-region
        dired-undo
        electric-newline-and-maybe-indent
        end-of-buffer
        end-of-visual-line
        forward-sentence
        isearch-delete-char
        isearch-forward-regexp
        isearch-printing-char
        jump-char-process-char
        kill-region
        kmacro-end-or-call-macro
        mouse-set-region
        neotree-rename-node
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        reindent-then-newline-and-indent
        sh-assignment
        tab-to-tab-stop
        wdired-downcase-word
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        beginning-of-visual-line
        c-electric-pound
        c-electric-star
        coffee-dedent-line-backspace
        dired-unmark-all-files
        dired-unmark-backward
        isearch-abort
        scroll-right
        sgml-slash
        ))
